services:
  # Backend API service
  - type: web
    name: realestate-api
    env: docker
    rootDir: RealestateApiServer
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/realestate_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: Ashking@123

  # Frontend service
  - type: static
    name: realestate-frontend
    rootDir: realestate-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://realestate-api.onrender.com 